server:  
  port: ${PORT:9400}

spring:  
  application:
    name: product-service

endpoints:
    shutdown:
      enabled: true
      sensitive: false

envoy:
  discovery:
    url: ${DISCOVERY_URL:http://localhost:9200}