server:  
  port: ${PORT:9300}

spring:  
  application:
    name: person-service

endpoints:
  shutdown:
    enabled: true
    sensitive: false

envoy:
  discovery:
    url: ${DISCOVERY_URL:http://localhost:9200}